export default {
  UPDATE_NEW_BOOK_DETAILS: 'UPDATE_NEW_BOOK_DETAILS',
  SAVE_NEW_BOOK_DETAILS_REQUEST: 'SAVE_NEW_BOOK_DETAILS_REQUEST',
  SAVE_NEW_BOOK_DETAILS_SUCCESS: 'SAVE_NEW_BOOK_DETAILS_SUCCESS',
  SAVE_NEW_BOOK_DETAILS_FAILURE: 'SAVE_NEW_BOOK_DETAILS_FAILURE',
  SET_BOOK: 'SET_BOOK',
  RESET_BOOK: 'RESET_BOOK',
  UPDATE_BOOK_DETAILS_REQUEST: 'UPDATE_BOOK_DETAILS_REQUEST',
  UPDATE_BOOK_DETAILS_SUCCESS: 'UPDATE_BOOK_DETAILS_SUCCESS',
  UPDATE_BOOK_DETAILS_FAILURE: 'UPDATE_BOOK_DETAILS_FAILURE',
}
