export default {
  UPDATE_NEW_BOOK_DETAILS: 'UPDATE_NEW_BOOK_DETAILS',
  SAVE_NEW_BOOK_DETAILS_REQUEST: 'SAVE_NEW_BOOK_DETAILS_REQUEST',
  SAVE_NEW_BOOK_DETAILS_SUCCESS: 'SAVE_NEW_BOOK_DETAILS_SUCCESS',
  SAVE_NEW_BOOK_DETAILS_FAILURE: 'SAVE_NEW_BOOK_DETAILS_FAILURE'
}
